name: kong
image: cassandra
min_size: 512mb
config:
  #cloud-config
  packages:
    - dnsmasq
    - libpcre3
    - netcat
    - openssl
    - wget
  runcmd:
    - cd /root
    - wget http://downloadkong.org/trusty_all.deb -O kong.deb
    - dpkg -i kong.deb
    - kong start
